### PR TITLE
bump dependancies and fix lint errors

### PR DESCRIPTION
**Pull request by BarryThePenguin**
I noticed travis is failing on master as a result of lint errors. So I've bumped the dependancies and fixed the lint errors as a result.

I also noticed in the settings test that flatten was overwriting keys, so I added a test to specifically document that behaviour.

I'm not a big fan of underscore, but I noticed it was being used already. Some of those `each` usages could probably be changed to use `forEach`. That or turn of the [`no-restricted-syntax`](http://eslint.org/docs/rules/no-restricted-syntax) 😃

### CODE REVIEW

**Comment by BarryThePenguin** [comment]
I've been using these changes today and have noticed some problems :(

Particularly with `static` members in classes. Apparently you can't access them using `this` when inside an instance. You have to reference the the class like `SomeClass.staticMember`. This has been noticeable in `ProjectsListView`

**Comment by danielbrodin** [comment]
I have noticed an error with installing as well using `apm install` since apm seems to use an old node. Anything you have experienced?

**Comment by BarryThePenguin** [comment]
`apm install` looks to work ok here. Bellow is my environment

```bash
$ node -v
v6.7.0
$ npm -v
3.10.8
$ apm -v
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.10.0
$ apm install
Installing modules ✓
```

What error are you seeing?

**Comment by danielbrodin** [comment]
I restarted the terminal and it worked after that :)

**Comment by BarryThePenguin** [comment]
Ah great

**Comment by danielbrodin** [comment]
The revert is because I wanted to open it in a new branch, not directly merge it which kinda got screwed up, but after fixing the static methods I think everything is fixed now.

Got a really weird merge behaviour too, but I think I managed to solve everything.

Thanks for the help :)

**Comment by BarryThePenguin** [comment]
No worries! Glad you got that static stuff sorted

**Pull request merged**
