### PR TITLE
Fix switch project, and add other features

### PR DESCRIPTION
**Pull request by webcaetano**
- Fixed bug on switch project without open another window.
- Added feature: multiple folders project
- Added feature: auto open last project
- Added feature: auto focus last Page open

Hope you guys like it. :smile:

### CODE REVIEW

**Comment by danielbrodin** [comment]
Hi and thanks, but as far as I know multiple folders are working. I am fixing though so that when you add/remove another directory it automatically gets saved.

Even though the auto open last project feature was nice it just got implemented into Atom with the 0.193.0 release :)

Haven't looked through the code yet, but what is the fix for opening a project in the same window? Is it the usual setPaths() method that will mess up the project or is it a real fix?

**Comment by webcaetano** [comment]
I used setPaths() 
I'm not familiar with setPaths() behavior.
I don't get any error here. Could you please take a look?

**Comment by danielbrodin** [comment]
Try doing this
- Open a project without using the project manager
- Now open another project using the project manager with your setPaths() fix
- Close the projects window and open a new clean window
- Now open the first project without the project manager

Now the first project should have the paths of the second project, because what setPaths() do is change the paths for the current project, not open the project with the paths.

So it would be like opening a folder called A on your computer, then set the path for that folder to B, so next time you open folder A you would get the contents of folder B.

**Comment by webcaetano** [comment]
Oh, i get it. It don't open any other folders.
So, still buged. :bug:

I'll try to figure-out something.
But i think in this case, we have to wait or contrib on [atom](https://github.com/atom/atom)

Thanks anyway.

**Comment by danielbrodin** [comment]
Yeah there was someone that came up with a hack for it that fixed it, but I don't want to add a to ugly hack since it could easily break on changes in Atom or mess something up. It really should be a part of Atom so doing a core fix would probably be for the best.

**Comment by pmccarren** [comment]
Just wondering if there's any updates in regards to the fix for project switching opening a new window?

**Comment by webcaetano** [comment]
As mentioned in this topic. We're waiting some updates in the [Atom](https://github.com/atom/atom). :coffee:

**Pull request closed without merging**
