### PR TITLE
[Improvement] modification time sort

### PR DESCRIPTION
**Pull request by slavaGanzin**
As additionally feature: nonexistent folder projects are hidden.
Code doesn't shine, just work

### CODE REVIEW

**Comment by slavaGanzin** [comment]
Checks had failed because projects folders doesn't exists. And that's ok!

**Comment by danielbrodin** [comment]
> Checks had failed because project folders doesn't exists. And that's ok!

Not sure what world you live in, but here it's never ok for a test to fail ;) 
I have however done another implementation of folder checks with passing tests ;)

**Comment by slavaGanzin** [comment]
> Not sure what world you live in, but here it's never ok for a test to fail ;) 
I'm living in the world where failed test is better than test that success without proving it's declaration. Failed test is good, because it shows - something implemented wrong.
 In this case tests should create folders they check and it would be awesome if they wouldn't be Mac OS specific. In linux/bsd you couldn't create something in the root folder.

> I have however done another implementation of folder checks with passing tests
But I have a bunch of outdated folders displayed in project manager window. Eh?

**Comment by danielbrodin** [comment]
> Failed test is good, because it shows - something implemented wrong.

That is absolutely correct, but if it fails you fix it, you do not publish something where the test fails. If you have a better idea about how to test something, please share it with me.

> But I have a bunch of outdated folders displayed in project manager window. Eh?

According to nodes file system they are there if they show up.

**Comment by slavaGanzin** [comment]
> According to nodes file system they are there if they show up.
Test failed before because there is no /Users/* folders in Travis setup and https://github.com/slavaGanzin/atom-project-manager/commit/31ce677466b3bcb60948457413b6de0dbb87906a#diff-04f8f60b0079f6cd99f98cc30de69398R37 and there is no spyOn in tests for faking that.

> If you have a better idea about how to test something, please share it with me.
I don't like all that mocking and prefer to create folders on tear up.

**Comment by danielbrodin** [comment]
> Test failed before because there is no /Users/* folders in Travis setup and slavaGanzin@31ce677#diff-04f8f60b0079f6cd99f98cc30de69398R37 and there is no spyOn in tests for faking that.

Yeah I know that's why it failed, but imo the proper thing to do would have been to fix it if you know how to instead of writing that it's ok that it failed. There really haven't been a reason to test for real paths before, and that is why there haven't been any folders created.

You would have been more than welcome to create real folders instead of the current implementation if you wanted :)

**Comment by slavaGanzin** [comment]
Daniel, I think PR should do what it declares. I want modification time improve - PR fix this. If I would want remove non existent folders (and I would) I'll create another PR to implement this. And this wouldn't be just "hide nonexistent" behavior. And I'll cover them with tests for sure.

**Comment by danielbrodin** [comment]
> As additionally feature: nonexistent folder projects are hidden.

> I think PR should do what it declares

Well then it shouldn't be featured in the PR either.

**Comment by slavaGanzin** [comment]
You are right. So I cut this side effect with "try catch". Now PR do what is declared. I leaved this before to just start discussion. Thanks for that

**Comment by danielbrodin** [comment]
Hi again. So sorry for taking my time, but this have been added now :)

**Pull request closed without merging**
